In [1]:
!pip install numpy
import numpy as np 

In [3]:
data=np.array([[10,20,30],[40,50,60],[70,80,90]]) #initializing a 2D array using array function
print("Data array:\n", data)

Data array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
#Row-wise sum of the 2D array
row_sum=np.sum(data, axis=1)
print("Row-wise sum:\n", row_sum)

#Column-wise sum of the 2D array
col_sum=np.sum(data,axis=0)
print("Column-wise sum:\n", col_sum)

#Minimum value in the 2D array
min_value=np.min(data)
print("Minimum value in the array:", min_value)

#Maximum value in the 2D array
max_value=np.max(data)
print("Maximum value in the array:", max_value)

#Mean value of the 2D array
mean_value=np.mean(data)
print("Overall Mean value of the array:", mean_value)

Row-wise sum:
 [ 60 150 240]
Column-wise sum:
 [120 150 180]
Minimum value in the array: 10
Maximum value in the array: 90
