In [3]:
!pip install numpy
import numpy as np

  Using cached numpy-2.4.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.3-cp313-cp313-win_amd64.whl (12.3 MB)


In [ ]:
array1=np.arange(1,11) #creating an array of numbers from 1 to 10 using arange function
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
array2=np.arange(1,10).reshape(3,3) #creating an array of numbers from 1 to 9 using arange function and shape function to reshape it into a 3x3 array
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
array3=np.array([10,20,30,40,50]) #creating an array of numbers using array function
print(array3)

[10 20 30 40 50]


In [12]:
print("Shape of array1:", array1.shape) #to check the shape of the array1
print("Shape of array2:", array2.shape) #to check the shape of the array2
print("Shape of array3:", array3.shape) #to check the shape of the array3

Shape of array1: (10,)
Shape of array2: (3, 3)
Shape of array3: (5,)


In [11]:
print("Datatype of array1:", array1.dtype) #to check the data type of the array1
print("Datatype of array2:", array2.dtype) #to check the data type of the array2
print("Datatype of array3:", array3.dtype) #to check the data type of the array3

Datatype of array1: int64
Datatype of array2: int64
Datatype of array3: int64
